# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Reference'
  link: '/reference'
- label: Example
  items:
    - label: 'Lesson 1'
      link: '/example/l1'
    - label: 'Lesson 2'
      link: '/example/l2'
